[package]
name = "grnull"
version = "0.1.0"
edition = "2021"

[dependencies]
malloc = { git = "https://github.com/os-module/domain-lib" }
corelib = { path = "../../../../domain-lib/corelib", features = ["blk-panic"] }
basic = { path = "../../../../domain-lib/basic",  default-features = false  }
shared_heap = { git = "https://github.com/os-module/domain-lib" }
interface = { path = "../../../../domain-lib/interface",  features = ["domain"]  }
storage = { git = "https://github.com/os-module/domain-lib", features = ["impl"] }
# storage = { path = "../../../../domain-lib/storage", features = ["impl"] }
rnull = { path = "../rnull" }

[features]
default = ["rust-unwind-time"]
rust-unwind = []
rust-unwind-time = []