[package]
name = "rnull"
version = "0.1.0"
edition = "2021"

[dependencies]
basic = { path = "../../../../domain-lib/basic" }
interface = { path = "../../../../domain-lib/interface" }
shared_heap = { git = "https://github.com/os-module/domain-lib" }
spin = "0.9.8"

kmacro = { path = "../../../../kmacro" }
pinned-init = { git = "https://github.com/Godones/pinned-init", default-features = false, features = ["alloc"] }
storage = { git = "https://github.com/os-module/domain-lib", features = ["impl"] }
# storage = { path = "../../../../domain-lib/storage", features = ["impl"] }
null = { path = "../../null/null", optional = true }
log = "0"


[features]
default = []
multi_domain_no = ["dep:null"]
multi_domain = []
