[package]
name = "gnull"
version = "0.1.0"
edition = "2021"

[dependencies]
malloc = { git = "https://github.com/os-module/domain-lib" }
corelib = { path = "../../../../domain-lib/corelib" }
basic = { path = "../../../../domain-lib/basic",  default-features = false  }
shared_heap = { git = "https://github.com/os-module/domain-lib" }
interface = { path = "../../../../domain-lib/interface",  features = ["domain"]  }
storage = { git = "https://github.com/os-module/domain-lib", features = ["impl"] }

null = { path = "../null" }


[features]
default = ["rust-unwind"]
rust-unwind = []
